app/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from . import db
from .models import User, Transaction, Budget, SavingsGoal
from .forms import LoginForm, RegistrationForm, TransactionForm, BudgetForm, SavingsGoalForm,EditTransactionForm,EditBudgetForm, EditSavingsGoalForm
from werkzeug.urls import url_parse
from flask import Blueprint

bp = Blueprint('main', __name__)

@bp.route('/')
def homepage():
    return render_template('homepage.html')

@bp.route('/index')
@login_required
def index():
    transactions = Transaction.query.filter_by(user_id=current_user.id).all()
    budgets = Budget.query.filter_by(user_id=current_user.id).all()
    savings_goals = SavingsGoal.query.filter_by(user_id=current_user.id).all()
    total_transactions_amount = sum(transaction.amount for transaction in transactions)
    
    return render_template('index.html', transactions=transactions, budgets=budgets, savings_goals=savings_goals, total_transactions_amount=total_transactions_amount)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)

@bp.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('main.homepage'))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)

@bp.route('/add_transaction', methods=['GET', 'POST'])
@login_required
def add_transaction():
    form = TransactionForm()
    if form.validate_on_submit():
        transaction = Transaction(amount=form.amount.data, category=form.category.data, user_id=current_user.id)
        db.session.add(transaction)
        db.session.commit()
        flash('Transaction added successfully')
        return redirect(url_for('main.index'))
    return render_template('add_transaction.html', title='Add Transaction', form=form)

@bp.route('/edit_transaction/<int:transaction_id>', methods=['GET', 'POST'])
@login_required
def edit_transaction(transaction_id):
    transaction = Transaction.query.get_or_404(transaction_id)
    if transaction.user_id != current_user.id:
        flash('You do not have permission to edit this transaction.')
        return redirect(url_for('main.index'))

    form = EditTransactionForm(obj=transaction)
    if form.validate_on_submit():
        transaction.amount = form.amount.data
        transaction.category = form.category.data
        db.session.commit()
        flash('Transaction updated successfully.')
        return redirect(url_for('main.index'))
    
    return render_template('edit_transaction.html', title='Edit Transaction', form=form, transaction_id=transaction_id)

@bp.route('/add_budget', methods=['GET', 'POST'])
@login_required
def add_budget():
    form = BudgetForm()
    if form.validate_on_submit():
        budget = Budget(category=form.category.data, amount=form.amount.data, user_id=current_user.id)
        db.session.add(budget)
        db.session.commit()
        flash('Budget added successfully')
        return redirect(url_for('main.index'))
    return render_template('add_budget.html', title='Add Budget', form=form)

@bp.route('/add_savings_goal', methods=['GET', 'POST'])
@login_required
def add_savings_goal():
    form = SavingsGoalForm()
    if form.validate_on_submit():
        savings_goal = SavingsGoal(goal=form.goal.data, amount=form.amount.data, user_id=current_user.id)
        db.session.add(savings_goal)
        db.session.commit()
        flash('Savings Goal added successfully')
        return redirect(url_for('main.index'))
    return render_template('add_savings_goal.html', title='Add Savings Goal', form=form)

@bp.route('/delete_transaction/<int:transaction_id>', methods=['POST'])
@login_required
def delete_transaction(transaction_id):
    transaction = Transaction.query.get_or_404(transaction_id)
    if transaction.user_id != current_user.id:
        flash('You do not have permission to delete this transaction.')
        return redirect(url_for('main.index'))
    db.session.delete(transaction)
    db.session.commit()
    flash('Transaction deleted successfully')
    return redirect(url_for('main.index'))

@bp.route('/delete_budget/<int:budget_id>', methods=['POST'])
@login_required
def delete_budget(budget_id):
    budget = Budget.query.get_or_404(budget_id)
    if budget.user_id != current_user.id:
        flash('You do not have permission to delete this budget.')
        return redirect(url_for('main.index'))
    db.session.delete(budget)
    db.session.commit()
    flash('Budget deleted successfully')
    return redirect(url_for('main.index'))

@bp.route('/edit_budget/<int:budget_id>', methods=['GET', 'POST'])
@login_required
def edit_budget(budget_id):
    budget = Budget.query.get_or_404(budget_id)
    if budget.user_id != current_user.id:
        flash('You do not have permission to edit this budget.')
        return redirect(url_for('main.index'))

    form = EditBudgetForm(obj=budget)
    if form.validate_on_submit():
        budget.category = form.category.data
        budget.amount = form.amount.data
        db.session.commit()
        flash('Budget updated successfully.')
        return redirect(url_for('main.index'))
    
    return render_template('edit_budget.html', title='Edit Budget', form=form, budget_id=budget_id)

@bp.route('/delete_savings_goal/<int:savings_goal_id>', methods=['POST'])
@login_required
def delete_savings_goal(savings_goal_id):
    savings_goal = SavingsGoal.query.get_or_404(savings_goal_id)
    if savings_goal.user_id != current_user.id:
        flash('You do not have permission to delete this savings goal.')
        return redirect(url_for('main.index'))
    db.session.delete(savings_goal)
    db.session.commit()
    flash('Savings goal deleted successfully')
    return redirect(url_for('main.index'))

@bp.route('/edit_savings_goal/<int:savings_goal_id>', methods=['GET', 'POST'])
@login_required
def edit_savings_goal(savings_goal_id):
    savings_goal = SavingsGoal.query.get_or_404(savings_goal_id)
    if savings_goal.user_id != current_user.id:
        flash('You do not have permission to edit this savings goal.')
        return redirect(url_for('main.index'))

    form = EditSavingsGoalForm(obj=savings_goal)
    if form.validate_on_submit():
        savings_goal.goal = form.goal.data
        savings_goal.amount = form.amount.data
        savings_goal.current_amount = form.current_amount.data
        db.session.commit()
        flash('Savings goal updated successfully.')
        return redirect(url_for('main.index'))
    
    return render_template('edit_savings_goal.html', title='Edit Savings Goal', form=form, savings_goal_id=savings_goal_id)

app/templates/add_budget.html
{% extends 'base.html' %}

{% block title %}Add Budget{% endblock %}

{% block content %}
<h1 class="h1edit">Add Budget</h1>
<form action="{{ url_for('main.add_budget') }}" method="post">
    {{ form.hidden_tag() }}
    <div>
        {{ form.category.label }}
        {{ form.category(class="editform") }}
        {% for error in form.category.errors %}
            <span class="error">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.amount.label }}
        {{ form.amount(class="editform") }}
        {% for error in form.amount.errors %}
            <span class="error">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div >
        <p> {{ form.submit(class="addButton") }}</p>
       
    </div>
</form>
{% endblock %}

app/templates/add_savings_goal.html
{% extends 'base.html' %}

{% block title %}Add Savings Goal{% endblock %}

{% block content %}
<h1 class="h1edit">Add Savings Goal</h1>
<form action="{{ url_for('main.add_savings_goal') }}" method="post">
    {{ form.hidden_tag() }}
    <div>
        {{ form.goal.label }}
        {{ form.goal(class="editform") }}
        {% for error in form.goal.errors %}
            <span class="error">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.amount.label }}
        {{ form.amount(class="editform") }}
        {% for error in form.amount.errors %}
            <span class="error">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        <p> {{ form.submit(class="addButton") }}</p>
    </div>
</form>
{% endblock %}

app/templates/add_transaction.html
{% extends 'base.html' %}

{% block title %}Add Transaction{% endblock %}

{% block content %}
<h1 class="h1edit">Add Transaction</h1>
<form action="{{ url_for('main.add_transaction') }}" method="post">
    {{ form.hidden_tag() }}
    <div>
        {{ form.amount.label }}
        {{ form.amount(class="editform")}}
        {% for error in form.amount.errors %}
            <span class="error">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.category.label }}
        {{ form.category(class="editform") }}
        {% for error in form.category.errors %}
            <span class="error">[{{ error }}]</span>
        {% endfor %}
    </div>
  
    <div>
        <p> {{ form.submit(class="addButton") }}</p>
    </div>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Finance App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  
</head>
<body>
    <header>
        <nav>
           
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('main.index') }}">Home</a>
                <a href="{{ url_for('main.add_transaction') }}">Add Transaction</a>
                <a href="{{ url_for('main.add_budget') }}">Add Budget</a>
                <a href="{{ url_for('main.add_savings_goal') }}">Add Savings Goal</a>
                <a href="{{ url_for('main.logout') }}">Logout</a>
            {% else %}
                <a href="{{ url_for('main.login') }}">Login</a>
                <a href="{{ url_for('main.register') }}">Register</a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
  
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

app/templates/edit_budget.html
{% extends "base.html" %}

{% block title %}Edit Budget{% endblock %}

{% block content %}
<h1 class="h1edit">Edit Budget</h1>
<form  action="{{ url_for('main.edit_budget', budget_id=budget_id) }}" method="post">
    {{ form.hidden_tag() }}
    <p >
        {{ form.category.label }}<br>
        {{ form.category(class="editform") }}<br>
        {% for error in form.category.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.amount.label }}<br>
        {{ form.amount(class="editform") }}<br>
        {% for error in form.amount.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p><input type="submit" value="Update Budget" class="btn btn-primary"></p>
</form>
{% endblock %}

app/templates/edit_savings_goal.html
{% extends "base.html" %}

{% block title %}Edit Savings Goal{% endblock %}

{% block content %}
<h1 class="h1edit">Edit Savings Goal</h1>
<form action="{{ url_for('main.edit_savings_goal', savings_goal_id=savings_goal_id) }}" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.goal.label }}<br>
        {{ form.goal(class="editform") }}<br>
        {% for error in form.goal.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.amount.label }}<br>
        {{ form.amount(size=32) }}<br>
        {% for error in form.amount.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.current_amount.label }}<br>
        {{ form.current_amount(size=32) }}<br>
        {% for error in form.current_amount.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p><input type="submit" value="Update Savings Goal" class="btn btn-primary"></p>
</form>
{% endblock %}

app/templates/edit_transaction.html
{% extends "base.html" %}

{% block title %}Edit Transaction{% endblock %}

{% block content %}
<h1 class="h1edit">Edit Transaction</h1>
<form action="{{ url_for('main.edit_transaction', transaction_id=transaction_id) }}" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.amount.label }}<br>
        {{ form.amount(class="editform") }}<br>
        {% for error in form.amount.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.category.label }}<br>
        {{ form.category(class="editform") }}<br>
        {% for error in form.category.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p><input type="submit" value="Update Transaction" class="btn btn-primary"></p>
</form>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome, {{ current_user.username }}!</h1>

<h2>Transactions</h2>
<ul>
    {% for transaction in transactions %}
        <li>{{ transaction.date }}: {{ transaction.category }} - ${{ transaction.amount }}</li>
    {% endfor %}
</ul>

<h2>Budgets</h2>
<ul>
    {% for budget in budgets %}
        <li>{{ budget.category }}: ${{ budget.amount }}</li>
    {% endfor %}
</ul>

<h2>Savings Goals</h2>
<ul>
    {% for goal in savings_goals %}
        <li>{{ goal.goal }}: ${{ goal.amount }} (Current: ${{ goal.current_amount }})</li>
    {% endfor %}
</ul>

<a href="{{ url_for('main.add_transaction') }}">Add Transaction</a>
<a href="{{ url_for('main.add_budget') }}">Add Budget</a>
<a href="{{ url_for('main.add_savings_goal') }}">Add Savings Goal</a>
{% endblock %}

app/templates/homepage.html
<!-- homepage.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Your App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
    <div class="container">
        <header>
            <h1>Welcome VividFin</h1>
        </header>
        <section>
            <p>Track your finances </p>
            <div class="button-group">
                <a href="{{ url_for('main.login') }}" class="btn">Log In</a>
                <a href="{{ url_for('main.register') }}" class="btn">Register</a>
            </div>
        </section>
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<h1>Welcome, {{ current_user.username }}!</h1>

<div class="section">
    <div class="flex-container">
        <h2>Transactions</h2>
        <a href="{{ url_for('main.add_transaction') }}" class="btn">Add Transaction</a>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Amount</th>
                <th>Category</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>${{ transaction.amount }}</td>
                <td>{{ transaction.category }}</td>
                <td>{{ transaction.date.strftime('%Y-%m-%d') }}</td>
                <td>
                    <form action="{{ url_for('main.delete_transaction', transaction_id=transaction.id) }}" method="post" style="display:inline;">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type="submit" value="Delete" class=" btn-danger ">
                    </form>
                    <a href="{{ url_for('main.edit_transaction', transaction_id=transaction.id) }}" class=" btn-sm">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <th>Total:${{ total_transactions_amount }}</th>
        </tfoot>
    </table>
</div>

<div class="section">
    <div class="flex-container">
        <h2>
            Budgets
                  
        </h2>
        <a href="{{ url_for('main.add_budget') }}" class="btn">Add Budget</a>
            
    </div>
   
    <table>
        <thead>
            <tr>
                <th>Amount</th>
                <th>Category</th> 
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for budget in budgets %}
            <tr>
                <td>${{ budget.amount }}</td>
                <td>{{ budget.category }}</td>
                <td>
                    <form action="{{ url_for('main.delete_budget', budget_id=budget.id) }}" method="post" style="display:inline;">
                      
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type="submit" value="Delete" class=" btn-danger ">
                    </form>
                    <a href="{{ url_for('main.edit_budget', budget_id=budget.id) }}" class="btn-sm">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <th>Total:${{ total_transactions_amount }}</th>
        </tfoot>
    </table>
</div>

<div class="section">
    <div class="flex-container">
        <h2>
            Savings Goals 
        
            </h2>
            <a href="{{ url_for('main.add_savings_goal') }}" class="btn">Add Savings Goal</a>
    </div>

     
       
    <table>
        <thead>
            <tr>
                <th>Goal</th>
                <th>Amount</th>
                <th>Current Amount Saved</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for goal in savings_goals %}
            <tr>
                <td>{{ goal.goal }}</td>
                <td>${{ goal.amount }}</td>
                <td>${{ goal.current_amount }}</td>
                <td>
                    <form action="{{ url_for('main.delete_savings_goal', savings_goal_id=goal.id) }}" method="post" style="display:inline;">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type="submit" value="Delete" class=" btn-danger ">
                    </form>
                    <a href="{{ url_for('main.edit_savings_goal', savings_goal_id=goal.id) }}" class="btn-sm">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <section>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class="flashes">
                    {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        <form action="{{ url_for('main.login') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}<br>
                {{ form.username(class_="form-control", size=32) }}<br>
                {% for error in form.username.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password.label }}<br>
                {{ form.password(class_="form-control", size=32) }}<br>
                {% for error in form.password.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.remember_me() }}
                {{ form.remember_me.label }}
            </div>
            <div class="button-group">
                {{ form.submit(class_="btn") }}
            </div>
        </form>
        <p>Don't have an account? <a href="{{ url_for('main.register') }}">Register here</a>.</p>
    </section>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<h1>Register</h1>
<form action="{{ url_for('main.register') }}" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}<br>
        {% for error in form.username.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.email.label }}<br>
        {{ form.email(size=32) }}<br>
        {% for error in form.email.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
        {% for error in form.password.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label }}<br>
        {{ form.password2(size=32) }}<br>
        {% for error in form.password2.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}